version: "3"

services:
  redis:
    image: redis:latest
    restart: always

  db:
    image: mongo:latest
    restart: always
    volumes:
      - screeps_mongo:/data/db

  screeps:
    image: demannu/screeps-docker:latest
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "21025:21025"
    environment:
      # Required
      STEAM_API_KEY: your_real_key
      # Optional
      SCREEPS_PORT: 21025
      SCREEPS_HOST: 0.0.0.0
      SCREEPS_PASS: your_real_password
      SCREEPS_CLI_PORT: 21026
      SCREEPS_CLI_HOST: localhost
    volumes:
      - screeps_world:/world

volumes:
  screeps_mongo:
  screeps_world:
