apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: screeps-mongo
  name: screeps-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
