apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: screeps-world
  name: screeps-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
