---
# Install K3s on Worker Node
tasks:
  - name: Install K3s agent on worker
    shell: |
      curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ token }} sh -
    args:
      creates: /usr/local/bin/k3s