apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: "7.5.2"
    helm:
      valueFiles:
        - $kubernetes_homeNodes/argo/argo-cd/values.yaml

  - repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    ref: kubernetes_homeNodes

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
