apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
spec:
  project: default


  destination: 
    server: https://kubernetes.default.svc
    namespace: cert-manager
    
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: "1.15.0"
    helm:
      valueFiles:
        - $kubernetes_homeNodes/argo/cert-manager/values.yaml

  - repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    ref: kubernetes_homeNodes
    path: argo/cert-manager


  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
