apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: "0.10.3"
    helm:
      valueFiles:
        - $kubernetes_homeNodes/argo/external-secrets/values.yaml

  - repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    ref: kubernetes_homeNodes

  destination: 
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
