apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    path: argo/external-secrets
  destination: 
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
