apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: "4.11.2"
    helm:
      valueFiles:
        - $kubernetes_homeNodes/ingress-nginx/values.yaml

  - repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    ref: kubernetes_homeNodes

  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true