apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@bitbucket.org:smartcommerce_se/foerch-argocd.git
    targetRevision: main
    path: argo/ingress-nginx

  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true



#----------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  generators:
    - git:
        repoURL: git@bitbucket.org:smartcommerce_se/foerch-argocd.git
        revision: master
        files:
          - path: "ingress-nginx/cluster-config/**/config.json"
  template:
    metadata:
      name: 'ingress-nginx-{{cluster.name}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: '{{cluster.address}}'
        namespace: ingress-nginx
      source:
        repoURL: git@bitbucket.org:smartcommerce_se/foerch-argocd.git
        targetRevision: master
        path: ingress-nginx
        helm:
          releaseName: ingress-nginx
