apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@bitbucket.org:smartcommerce_se/foerch-argocd.git
    targetRevision: main
    path: argo/ingress-nginx

  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true