
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: screeps-server-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    path: argo/screepsServer
  destination: 
    server: https://kubernetes.default.svc
    namespace: screeps-server

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true