apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
        namespace: ingress-nginx
      version: "4.0.0"
  valuesFrom:
    - kind: ConfigMap
      name: ingress-values