controller:
  replicaCount: 2
  minAvailable: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
        #additionalLabels:
        #   release: prometheus-operator
  service:
    type: NodePort
    nodePorts:
      # -- Node port allocated for the external HTTP listener. If left empty, the service controller allocates one from the configured node port range.
      http: 30080
      # -- Node port allocated for the external HTTPS listener. If left empty, the service controller allocates one from the configured node port range.
      https: 30443
      udp: 7777